# Site settings
title: bvallieres
email: Brice.Vallieres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  God please help me find purpose...but until then, let me help others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bvallieres.com" # the base hostname & protocol for your site
twitter_username: wireblitz
github_username:  bvallier
tagline: welp. help.
github: blog

# Build settings
markdown: kramdown

comments: true