# Site settings
title: bvallieres
email: Brice.Vallieres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Views are my own and admittedly biased.
baseurl: ""
images: "https://dl.dropboxusercontent.com/s/dv8fo6wlb14cv0p"
url: "https://bvallieres.com" # the base hostname & protocol for your site
twitter_username: wireblitz
github_username:  bvallier
tagline: wired. thoughts.
github: blog

# Build settings
markdown: kramdown

comments: true