# Site settings
title: bvallieres
email: Brice.Vallieres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  God please help me find purpose...but until then, let me help others.
baseurl: ""
images: "https://s3.amazonaws.com/bvallieres/images"
url: "https://bvallieres.com" # the base hostname & protocol for your site
twitter_username: wireblitz
github_username:  bvallier
tagline: wired. thoughts.
github: blog

# Build settings
markdown: kramdown

comments: true