# Site settings
title: bvallieres
email: Brice.Vallieres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  God please help me find purpose...but until then, let me help others.
baseurl: ""
images: "https://dl.dropboxusercontent.com/s/n9qcygy42pt54ik/"
url: "https://bvallieres.com" # the base hostname & protocol for your site
enforce_ssl: bvallieres.com
twitter_username: wireblitz
github_username:  bvallier
tagline: wired. thoughts.
github: blog

# Build settings
markdown: kramdown

comments: true